# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across node version 16.14.x
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ v13 ]
  pull_request:
    branches: [ v13 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
      env:
          DISCORD_BOT_EMBED_COLOR: ${{ secrets.DISCORD_BOT_EMBED_COLOR }}
          DISCORD_BOT_INVITE: ${{ secrets.DISCORD_BOT_INVITE }}
          DISCORD_BOT_OWNER_ID: ${{ secrets.DISCORD_BOT_OWNER_ID }}
          DISCORD_BOT_PREFIX: ${{ secrets.DISCORD_BOT_PREFIX }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_BOT_USERNAME: ${{ secrets.DISCORD_BOT_USERNAME }}
          EMOTE_LEFT: ${{ secrets.EMOTE_LEFT }}
          EMOTE_NO: ${{ secrets.EMOTE_NO }}
          EMOTE_OK: ${{ secrets.EMOTE_OK }}
          EMOTE_RIGHT: ${{ secrets.EMOTE_RIGHT }}
          GENIUS: ${{ secrets.GENIUS }}
          VERSION: ${{ secrets.VERSION }}
